### ISSUE TITLE
Configuration with Caddyfile?

### ISSUE THREAD

**Issue by adammakowskidev** [gerolf-vent/caddy-vault-storage#1]
Hi
Can this plugin be used with Caddyfile?  I don't see documentation.  Can you give an example?

Thx!

**Comment by adammakowskidev** [comment]
@gerolf-vent will I receive an answer?

**Comment by gerolf-vent** [comment]
Hey @adammakowskidev,

i finally got the time to write the Caddyfile support. I just released it in version [v1.2.0](https://github.com/gerolf-vent/caddy-vault-storage/releases/tag/v1.2.0). I hope that helps.

Best regards
